"""Render results/REPORT.md (and results/results.json) from the scoring pass."""
from __future__ import annotations

import json
from typing import Optional

from . import __version__
from .config import RESULTS_DIR
from .registry import benchmarks_available
from .scoring import score_structure


def _cell(b: Optional[dict]) -> str:
    if not b or not b.get("attempted"):
        return "—"
    mark = f"**{b['accuracy']:.1f}**" if b.get("accuracy") is not None else "—"
    cell = f"{mark} ({b['passed']}/{b['attempted']})"
    if b.get("status") == "partial":
        cell += " ⚠partial"
    if b.get("timeouts"):
        cell += f" ⏱{b['timeouts']}"
    return cell


def build_report(structure: dict, info: Optional[dict] = None) -> str:
    info = info or benchmarks_available()
    models = structure["models"]
    order = structure["order"]
    lines: list[str] = []
    A = lines.append

    A("# localbench report")
    A("")
    A(f"_generated by localbench {__version__} — run filter: "
      f"`{structure['run']}` — {structure['selected_records']} result rows, "
      f"runs on record: {', '.join(structure['runs_available']) or 'none'}_")
    A("")

    if not order:
        A("_No results yet. Run `python3 -m localbench run` first._")
        return "\n".join(lines) + "\n"

    # ---- headline --------------------------------------------------------
    A("## Headline")
    A("")
    A("| Model | Suite score | custom | known | benchmarks scored | Notes |")
    A("|---|---:|---:|---:|---:|---|")
    for slug in order:
        m = models[slug]
        suites = m.get("by_suite", {})
        note = m.get("endpoint_error") or ""
        if not note:
            partial = [n for n, b in m["benchmarks"].items()
                       if b.get("status") == "partial"]
            if partial:
                note = "partial: " + ", ".join(sorted(partial))
        score_txt = f"**{m['suite_score']:.1f}**" if m.get("suite_score") is not None else "—"
        A(f"| {m['name']} | {score_txt} "
          f"| {suites.get('custom', '—')} | {suites.get('known', '—')} "
          f"| {len(m.get('scored_benchmarks', []))} | {note} |")
    A("")

    # ---- per-benchmark matrix -------------------------------------------
    A("## Accuracy by benchmark")
    A("")
    A("| Benchmark | Suite | Weight | " + " | ".join(models[s]["name"] for s in order) + " |")
    A("|---|---|---:|" + "---|" * len(order))
    seen = []
    for slug in order:
        for name in models[slug]["benchmarks"]:
            if name not in seen:
                seen.append(name)
    def _key(n: str):
        i = info.get(n, {})
        return (i.get("suite", "") != "custom", i.get("suite", ""), n)
    for name in sorted(seen, key=_key):
        i = info.get(name, {})
        w = structure["weights"].get(name, 1.0)
        cells = [_cell(models[s]["benchmarks"].get(name)) for s in order]
        A(f"| {name} | {i.get('suite', '?')} | {w} | " + " | ".join(cells) + " |")
    A("")
    A("_Suite score = weighted mean of the per-benchmark accuracies above; "
      "weights come from `config/suite.json`. ⚠partial means fewer units were "
      "run than the benchmark was selected with._")
    A("")

    # ---- detail ----------------------------------------------------------
    A("## Detail")
    A("")
    for slug in order:
        m = models[slug]
        A(f"### {m['name']}")
        A("")
        if m.get("endpoint_error"):
            A(f"- endpoint failed to start: `{m['endpoint_error']}`")
            A("")
        for name in sorted(m["benchmarks"], key=lambda n: _key(n)):
            b = m["benchmarks"][name]
            if not b.get("attempted"):
                continue
            A(f"- **{name}** — {b['passed']}/{b['attempted']} "
              f"({b.get('accuracy')}%), weight {b.get('weight')}, "
              f"status {b.get('status')}"
              + (f", expected {b['expected']}" if b.get("expected") else "")
              + (f", {b['timeouts']} timeout(s)" if b.get("timeouts") else ""))
        A("")

    # ---- methodology -----------------------------------------------------
    A("## Methodology")
    A("")
    A("- Every unit — hand-built task or published benchmark item — runs through "
      "the same agentic harness: the Pi agent in a `bwrap` sandbox, thinking "
      "level `high`, fixed task-neutral system prompt.")
    A("- Contamination control: custom task directories are mounted read-only "
      "with `SOLUTION.md`, `verify.py` and `teardown.sh` masked out; sandbox "
      "`$HOME` is a scratch tmpfs holding only the provider registry; "
      "`--no-session --no-extensions --no-skills --no-context-files`.")
    A("- Graders are pure functions of the response text: `mcq`, `exact`, "
      "`math`, `code` (benchmark's own test suite, run without network), "
      "`ifeval` (vendored official Google checkers), or the custom task's own "
      "`verify.py`.")
    A("- One model resident at a time: all conflicting server units are stopped "
      "and VRAM drained before each endpoint start; identity confirmed via "
      "`/v1/models` plus a 1-token warm completion.")
    A("- Scores use the newest run per model unless `--run`/`--all-runs` says "
      "otherwise.")
    return "\n".join(lines) + "\n"


def write_report(structure: dict, info: Optional[dict] = None) -> tuple:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    md = build_report(structure, info)
    (RESULTS_DIR / "REPORT.md").write_text(md, encoding="utf-8")
    (RESULTS_DIR / "results.json").write_text(
        json.dumps(structure, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    return RESULTS_DIR / "REPORT.md", RESULTS_DIR / "results.json"


def make_structure(**kw) -> dict:
    return score_structure(**kw)
